class AppConstants {
  AppConstants._();

  static final List<Map<String, String>> currencies = [
    {'code': 'USD', 'name': 'United States Dollar (\$)', 'flag': '🇺🇸'},
    {'code': 'EUR', 'name': 'Euro (€)', 'flag': '🇪🇺'},
    {'code': 'JPY', 'name': 'Japanese Yen (¥)', 'flag': '🇯🇵'},
    {'code': 'GBP', 'name': 'British Pound (£)', 'flag': '🇬🇧'},
    {'code': 'AUD', 'name': 'Australian Dollar (A\$)', 'flag': '🇦🇺'},
    {'code': 'CAD', 'name': 'Canadian Dollar (C\$)', 'flag': '🇨🇦'},
    {'code': 'CHF', 'name': 'Swiss Franc (CHF)', 'flag': '🇨🇭'},
    {'code': 'CNY', 'name': 'Chinese Yuan (¥)', 'flag': '🇨🇳'},
    {'code': 'HKD', 'name': 'Hong Kong Dollar (HK\$)', 'flag': '🇭🇰'},
    {'code': 'NZD', 'name': 'New Zealand Dollar (NZ\$)', 'flag': '🇳🇿'},
    {'code': 'SEK', 'name': 'Swedish Krona (kr)', 'flag': '🇸🇪'},
    {'code': 'KRW', 'name': 'South Korean Won (₩)', 'flag': '🇰🇷'},
    {'code': 'SGD', 'name': 'Singapore Dollar (S\$)', 'flag': '🇸🇬'},
    {'code': 'NOK', 'name': 'Norwegian Krone (kr)', 'flag': '🇳🇴'},
    {'code': 'MXN', 'name': 'Mexican Peso (\$)', 'flag': '🇲🇽'},
    {'code': 'INR', 'name': 'Indian Rupee (₹)', 'flag': '🇮🇳'},
    {'code': 'RUB', 'name': 'Russian Ruble (₽)', 'flag': '🇷🇺'},
    {'code': 'ZAR', 'name': 'South African Rand (R)', 'flag': '🇿🇦'},
    {'code': 'TRY', 'name': 'Turkish Lira (₺)', 'flag': '🇹🇷'},
    {'code': 'BRL', 'name': 'Brazilian Real (R\$)', 'flag': '🇧🇷'},
    {'code': 'TWD', 'name': 'New Taiwan Dollar (NT\$)', 'flag': '🇹🇼'},
    {'code': 'DKK', 'name': 'Danish Krone (kr)', 'flag': '🇩🇰'},
    {'code': 'PLN', 'name': 'Polish Złoty (zł)', 'flag': '🇵🇱'},
    {'code': 'THB', 'name': 'Thai Baht (฿)', 'flag': '🇹🇭'},
    {'code': 'IDR', 'name': 'Indonesian Rupiah (Rp)', 'flag': '🇮🇩'},
    {'code': 'HUF', 'name': 'Hungarian Forint (Ft)', 'flag': '🇭🇺'},
    {'code': 'CZK', 'name': 'Czech Koruna (Kč)', 'flag': '🇨🇿'},
    {'code': 'ILS', 'name': 'Israeli New Shekel (₪)', 'flag': '🇮🇱'},
    {'code': 'CLP', 'name': 'Chilean Peso (\$)', 'flag': '🇨🇱'},
    {'code': 'PHP', 'name': 'Philippine Peso (₱)', 'flag': '🇵🇭'},
    {
      'code': 'AED',
      'name': 'United Arab Emirates Dirham (AED)',
      'flag': '🇦🇪',
    },
    {'code': 'COP', 'name': 'Colombian Peso (\$)', 'flag': '🇨🇴'},
    {'code': 'SAR', 'name': 'Saudi Riyal (SR)', 'flag': '🇸🇦'},
    {'code': 'MYR', 'name': 'Malaysian Ringgit (RM)', 'flag': '🇲🇾'},
    {'code': 'RON', 'name': 'Romanian Leu (lei)', 'flag': '🇷🇴'},
    {'code': 'EGP', 'name': 'Egyptian Pound (E£)', 'flag': '🇪🇬'},
    {'code': 'JOD', 'name': 'Jordanian Dinar (JD)', 'flag': '🇯🇴'},
    {'code': 'KWD', 'name': 'Kuwaiti Dinar (KD)', 'flag': '🇰🇼'},
    {'code': 'MAD', 'name': 'Moroccan Dirham (MAD)', 'flag': '🇲🇦'},
    {'code': 'QAR', 'name': 'Qatari Riyal (QR)', 'flag': '🇶🇦'},
    {'code': 'OMR', 'name': 'Omani Rial (OMR)', 'flag': '🇴🇲'},
    {'code': 'IQD', 'name': 'Iraqi Dinar (IQD)', 'flag': '🇮🇶'},
    {'code': 'SYP', 'name': 'Syrian Pound (SYP)', 'flag': '🇸🇾'},
    {'code': 'BHD', 'name': 'Bahraini Dinar (BD)', 'flag': '🇧🇭'},
    {'code': 'DZD', 'name': 'Algerian Dinar (DA)', 'flag': '🇩🇿'},
    {'code': 'TND', 'name': 'Tunisian Dinar (DT)', 'flag': '🇹🇳'},
    {'code': 'ERN', 'name': 'Eritrean Nakfa (Nkf)', 'flag': '🇪🇷'},
    {'code': 'ETB', 'name': 'Ethiopian Birr (Br)', 'flag': '🇪🇹'},
    {'code': 'FJD', 'name': 'Fiji Dollar (FJ\$)', 'flag': '🇫🇯'},
    {'code': 'FKP', 'name': 'Falkland Islands Pound (FK£)', 'flag': '🇫🇰'},
    {'code': 'FOK', 'name': 'Faroese Króna (kr)', 'flag': '🇫🇴'},
  ];

  static final List<Map<String, String>> languages = [
    {'name': 'English', 'code': 'en', 'flag': '🇺🇸'},
    {'name': 'French', 'code': 'fr', 'flag': '🇫🇷'},
    {'name': 'Arabic', 'code': 'ar', 'flag': '🇦🇪'},
    {'name': 'Italian', 'code': 'it', 'flag': '🇮🇹'},
    {'name': 'German', 'code': 'de', 'flag': '🇩🇪'},
  ];
}
