import 'package:expense_tracker_ar/core/utils/locale_keys.dart';

class AppConstants {
  AppConstants._();

  static final List<Map<String, String>> currencies = [
    {
      'code': 'USD',
      'name': 'United States Dollar (\$)',
      'flag': '🇺🇸',
      'symbol': '\$',
    },
    {'code': 'EUR', 'name': 'Euro (€)', 'flag': '🇪🇺', 'symbol': '€'},
    {'code': 'JPY', 'name': 'Japanese Yen (¥)', 'flag': '🇯🇵', 'symbol': '¥'},
    {'code': 'GBP', 'name': 'British Pound (£)', 'flag': '🇬🇧', 'symbol': '£'},
    {
      'code': 'AUD',
      'name': 'Australian Dollar (A\$)',
      'flag': '🇦🇺',
      'symbol': 'A\$',
    },
    {
      'code': 'CAD',
      'name': 'Canadian Dollar (C\$)',
      'flag': '🇨🇦',
      'symbol': 'C\$',
    },
    {
      'code': 'CHF',
      'name': 'Swiss Franc (CHF)',
      'flag': '🇨🇭',
      'symbol': 'CHF',
    },
    {'code': 'CNY', 'name': 'Chinese Yuan (¥)', 'flag': '🇨🇳', 'symbol': '¥'},
    {
      'code': 'HKD',
      'name': 'Hong Kong Dollar (HK\$)',
      'flag': '🇭🇰',
      'symbol': 'HK\$',
    },
    {
      'code': 'NZD',
      'name': 'New Zealand Dollar (NZ\$)',
      'flag': '🇳🇿',
      'symbol': 'NZ\$',
    },
    {
      'code': 'SEK',
      'name': 'Swedish Krona (kr)',
      'flag': '🇸🇪',
      'symbol': 'kr',
    },
    {
      'code': 'KRW',
      'name': 'South Korean Won (₩)',
      'flag': '🇰🇷',
      'symbol': '₩',
    },
    {
      'code': 'SGD',
      'name': 'Singapore Dollar (S\$)',
      'flag': '🇸🇬',
      'symbol': 'S\$',
    },
    {
      'code': 'NOK',
      'name': 'Norwegian Krone (kr)',
      'flag': '🇳🇴',
      'symbol': 'kr',
    },
    {
      'code': 'MXN',
      'name': 'Mexican Peso (\$)',
      'flag': '🇲🇽',
      'symbol': '\$',
    },
    {'code': 'INR', 'name': 'Indian Rupee (₹)', 'flag': '🇮🇳', 'symbol': '₹'},
    {'code': 'RUB', 'name': 'Russian Ruble (₽)', 'flag': '🇷🇺', 'symbol': '₽'},
    {
      'code': 'ZAR',
      'name': 'South African Rand (R)',
      'flag': '🇿🇦',
      'symbol': 'R',
    },
    {'code': 'TRY', 'name': 'Turkish Lira (₺)', 'flag': '🇹🇷', 'symbol': '₺'},
    {
      'code': 'BRL',
      'name': 'Brazilian Real (R\$)',
      'flag': '🇧🇷',
      'symbol': 'R\$',
    },
    {
      'code': 'TWD',
      'name': 'New Taiwan Dollar (NT\$)',
      'flag': '🇹🇼',
      'symbol': 'NT\$',
    },
    {
      'code': 'DKK',
      'name': 'Danish Krone (kr)',
      'flag': '🇩🇰',
      'symbol': 'kr',
    },
    {
      'code': 'PLN',
      'name': 'Polish Złoty (zł)',
      'flag': '🇵🇱',
      'symbol': 'zł',
    },
    {'code': 'THB', 'name': 'Thai Baht (฿)', 'flag': '🇹🇭', 'symbol': '฿'},
    {
      'code': 'IDR',
      'name': 'Indonesian Rupiah (Rp)',
      'flag': '🇮🇩',
      'symbol': 'Rp',
    },
    {
      'code': 'HUF',
      'name': 'Hungarian Forint (Ft)',
      'flag': '🇭🇺',
      'symbol': 'Ft',
    },
    {
      'code': 'CZK',
      'name': 'Czech Koruna (Kč)',
      'flag': '🇨🇿',
      'symbol': 'Kč',
    },
    {
      'code': 'ILS',
      'name': 'Israeli New Shekel (₪)',
      'flag': '🇮🇱',
      'symbol': '₪',
    },
    {
      'code': 'CLP',
      'name': 'Chilean Peso (\$)',
      'flag': '🇨🇱',
      'symbol': '\$',
    },
    {
      'code': 'PHP',
      'name': 'Philippine Peso (₱)',
      'flag': '🇵🇭',
      'symbol': '₱',
    },
    {
      'code': 'AED',
      'name': 'United Arab Emirates Dirham (AED)',
      'flag': '🇦🇪',
      'symbol': 'AED',
    },
    {
      'code': 'COP',
      'name': 'Colombian Peso (\$)',
      'flag': '🇨🇴',
      'symbol': '\$',
    },
    {'code': 'SAR', 'name': 'Saudi Riyal (SR)', 'flag': '🇸🇦', 'symbol': 'SR'},
    {
      'code': 'MYR',
      'name': 'Malaysian Ringgit (RM)',
      'flag': '🇲🇾',
      'symbol': 'RM',
    },
    {
      'code': 'RON',
      'name': 'Romanian Leu (lei)',
      'flag': '🇷🇴',
      'symbol': 'lei',
    },
    {
      'code': 'EGP',
      'name': 'Egyptian Pound (E£)',
      'flag': '🇪🇬',
      'symbol': 'E£',
    },
    {
      'code': 'JOD',
      'name': 'Jordanian Dinar (JD)',
      'flag': '🇯🇴',
      'symbol': 'JD',
    },
    {
      'code': 'KWD',
      'name': 'Kuwaiti Dinar (KD)',
      'flag': '🇰🇼',
      'symbol': 'KD',
    },
    {
      'code': 'MAD',
      'name': 'Moroccan Dirham (MAD)',
      'flag': '🇲🇦',
      'symbol': 'MAD',
    },
    {
      'code': 'QAR',
      'name': 'Qatari Riyal (QR)',
      'flag': '🇶🇦',
      'symbol': 'QR',
    },
    {
      'code': 'OMR',
      'name': 'Omani Rial (OMR)',
      'flag': '🇴🇲',
      'symbol': 'OMR',
    },
    {
      'code': 'IQD',
      'name': 'Iraqi Dinar (IQD)',
      'flag': '🇮🇶',
      'symbol': 'IQD',
    },
    {
      'code': 'SYP',
      'name': 'Syrian Pound (SYP)',
      'flag': '🇸🇾',
      'symbol': 'SYP',
    },
    {
      'code': 'BHD',
      'name': 'Bahraini Dinar (BD)',
      'flag': '🇧🇭',
      'symbol': 'BD',
    },
    {
      'code': 'DZD',
      'name': 'Algerian Dinar (DA)',
      'flag': '🇩🇿',
      'symbol': 'DA',
    },
    {
      'code': 'TND',
      'name': 'Tunisian Dinar (DT)',
      'flag': '🇹🇳',
      'symbol': 'DT',
    },
    {
      'code': 'ERN',
      'name': 'Eritrean Nakfa (Nkf)',
      'flag': '🇪🇷',
      'symbol': 'Nkf',
    },
    {
      'code': 'ETB',
      'name': 'Ethiopian Birr (Br)',
      'flag': '🇪🇹',
      'symbol': 'Br',
    },
    {
      'code': 'FJD',
      'name': 'Fiji Dollar (FJ\$)',
      'flag': '🇫🇯',
      'symbol': 'FJ\$',
    },
    {
      'code': 'FKP',
      'name': 'Falkland Islands Pound (FK£)',
      'flag': '🇫🇰',
      'symbol': 'FK£',
    },
    {
      'code': 'FOK',
      'name': 'Faroese Króna (kr)',
      'flag': '🇫🇴',
      'symbol': 'kr',
    },
  ];

  static final List<Map<String, String>> languages = [
    {
      'name': 'Arabic',
      'nameKey': LocaleKeys.arabic,
      'code': 'ar',
      'flag': '🇦🇪',
    },
    {
      'name': 'English',
      'nameKey': LocaleKeys.english,
      'code': 'en',
      'flag': '🇺🇸',
    },
  ];
  static final List<String> paymentTypes = [
    'Cash',
    'Credit Card',
    'Debit Card',
    'Bank Transfer',
    'UPI',
    'Wallet',
    'Cheque',
    'Net Banking',
  ];
}
